import styled from "@emotion/styled";
import TextLink from "../components/atom/TextLink";
import { LinkTextIcon } from "../assets/icons";
import Button from "../components/atom/Button";
import RadioButton from "../components/atom/RadioButton";

const ComponentPage = () => {
  return (
    <PageContainer>
      <ComponentTitle>Text Link</ComponentTitle>
      <ComponentContainer>
        <div>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="hover"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="pressed"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="visited"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="disabled"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="hover"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="pressed"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="visited"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="disabled"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="hover"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="pressed"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="visited"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="disabled"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
        </div>
        <div>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="hover"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="pressed"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="visited"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="disabled"
              $type="subtle"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="hover"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="pressed"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="visited"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="disabled"
              $type="subtle"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="hover"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="pressed"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="visited"
              $type="subtle"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="disabled"
              $type="subtle"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
        </div>
        <div>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="hover"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="pressed"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="visited"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="large"
              link="#"
              $state="disabled"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="hover"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="pressed"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="visited"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="medium"
              link="#"
              $state="disabled"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
          <ComponentsBox>
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="hover"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="pressed"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="visited"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
            <TextLink
              label="버튼"
              $size="small"
              link="#"
              $state="disabled"
              $type="subtle_none"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
        </div>
      </ComponentContainer>
      <ComponentTitle>Button</ComponentTitle>
      <ComponentContainer>
        <div>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $state="hover"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $state="focus"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $state="disabled"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $state="hover"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $state="focus"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $state="disabled"
            />
          </ComponentsBox>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="hover"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="focus"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="disabled"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="hover"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="focus"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="disabled"
            />
          </ComponentsBox>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="large"
              $iconPosition="right"
              $icon={LinkTextIcon}
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="large"
              $iconPosition="right"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
        </div>
        <div>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="medium"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="medium"
            />
          </ComponentsBox>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="filled"
              $size="small"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="filled"
              $size="small"
            />
          </ComponentsBox>
        </div>
        <div>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $state="hover"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $state="focus"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $state="disabled"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $state="hover"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $state="focus"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $state="disabled"
            />
          </ComponentsBox>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="hover"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="focus"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="disabled"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="hover"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="focus"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="pressed"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $iconPosition="left"
              $icon={LinkTextIcon}
              $state="disabled"
            />
          </ComponentsBox>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="large"
              $iconPosition="right"
              $icon={LinkTextIcon}
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="large"
              $iconPosition="right"
              $icon={LinkTextIcon}
            />
          </ComponentsBox>
        </div>
        <div>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="medium"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="medium"
            />
          </ComponentsBox>
          <ComponentsBox>
            <Button
              label="버튼"
              $type="primary"
              $style="outline"
              $size="small"
            />
            <Button
              label="버튼"
              $type="secondary"
              $style="outline"
              $size="small"
            />
          </ComponentsBox>
        </div>
      </ComponentContainer>
      <ComponentTitle>RadioButton</ComponentTitle>
      <ComponentContainer>
        <ComponentsBox>
          <RadioButton
            label="라디오 버튼"
            name="radio-group"
            value="option"
            $size="large"
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group1"
            value="option1"
            $size="medium"
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group2"
            value="option2"
            $size="medium"
            checked
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group3"
            value="option3"
            $size="medium"
            disabled
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group4"
            value="option4"
            $size="medium"
            checked
            disabled
          />
        </ComponentsBox>
        <ComponentsBox>
          <RadioButton
            label="라디오 버튼"
            name="radio-group5"
            value="option5"
            $size="large"
            helpText="도움말 텍스트"
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group5"
            value="option6"
            $size="medium"
            helpText="도움말 텍스트"
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group6"
            value="option7"
            $size="medium"
            helpText="도움말 텍스트"
            checked
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group7"
            value="option8"
            $size="medium"
            helpText="도움말 텍스트"
            disabled
          />
          <RadioButton
            label="라디오 버튼"
            name="radio-group8"
            value="option9"
            $size="medium"
            helpText="도움말 텍스트"
            checked
            disabled
          />
        </ComponentsBox>
      </ComponentContainer>
    </PageContainer>
  );
};

const PageContainer = styled.div`
  height: 100vh;
  padding: 30px;
`;

const ComponentContainer = styled.div`
  display: flex;
  flex-direction: column;
  gap: 20px;
  width: 100%;
  padding: 20px;
  border-radius: 15px;
  border: 2px dashed #8a949e;
`;

const ComponentsBox = styled.div`
  display: flex;
  gap: 30px;
  margin-bottom: 10px;
`;

const ComponentTitle = styled.p`
  font-size: 24px;
  color: #131416;
  font-weight: 700;
  margin: 15px 0;
`;

export default ComponentPage;
